### ISSUE TITLE
Error message in Mac OS

### ISSUE THREAD

**Issue by fuatsengul** [mtharrison/manray#2]
Hi @mtharrison,
I'm trying use this package but it is giving this error here on Mac OS, it's running good on linux, do you have any idea for possible fix here?

Note that I've run your example, so nothing bad in code.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Render failed (1 tries) Request details: {"url":"/tmp/3996bfc6-2fa3-46dc-ac2e-5002a7828126.html","quality":100,"format":"png","timeout":30000,"height":480,"width":640,"crop":{"top":0,"left":0},"filename":"/tmp/phantom-render-stream/36444.ecbffcaa18741e8326031fa1ea0afed2.png","id":"fed0f3cfe81b6b08c07160b1646a01ce","sent":1496157223886,"tries":1,"injectJs":[],"success":false}
    at Duplex.<anonymous> (/Users/fuatsengul/repo/node/node_modules/phantom-render-stream/index.js:263:28)
    at emitOne (events.js:96:13)
    at Duplex.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Duplex.Readable.push (_stream_readable.js:134:10)
    at /Users/fuatsengul/repo/node/node_modules/phantom-render-stream/index.js:183:13
    at Array.forEach (native)
    at Duplexify.<anonymous> (/Users/fuatsengul/repo/node/node_modules/phantom-render-stream/index.js:181:14)
    at emitNone (events.js:86:13)
    at Duplexify.emit (events.js:185:7)
```

**Comment by fuatsengul** [comment]
Never mind I solved by updating dependancies
